#########################################################################
# Title:            Community: Tdarr V2 Node                            #
# Author(s):        Visorak, Migz, Banjer                               #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  haveagitgat/tdarr_node:v2-preview                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
    
- name: Stop and remove any existing container
  docker_container:
    name: tdarrv2_node
    state: absent

- name: "Check if '/dev/dri' exists"
  stat:
    path: "/dev/dri"
  register: dev_dri

- name: Create tdarr directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/tdarrv2/cache
 
- name: Create and start container
  docker_container:
    name: tdarrv2_node
    image: haveagitgat/tdarr_node:v2-preview
    pull: yes
    env:
      NodeID: "cloudboxnode"
      nodeIP: "0.0.0.0"
      nodePort: "9276"
      serverIP: "0.0.0.0"
      serverPort: "8266"
      TZ: "{{ tz }}"
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      NVIDIA_DRIVER_CAPABILITIES: "{{ 'all' if gpu.nvidia | default(false) else omit }}"
      NVIDIA_VISIBLE_DEVICES: "{{ 'all' if gpu.nvidia | default(false) else omit }}"
    volumes:
      - "/mnt/unionfs/Media:/media"
      - "/opt/tdarrv2/cache:/transcode_cache"
      - "/mnt/unionfs/Media/Movies:/movies"
      - "/mnt/unionfs/Media/TV:/tv"
    devices: "{{ '/dev/dri:/dev/dri' if (gpu.intel and dev_dri.stat.exists) | default(false) else omit }}"      
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - tdarrv2_node
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
